service:
  name: go_test_backend
  grpc_addr: ":50051"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "root111"
  database: "postgres"
  sslmode: "disable"

migrations:
  dir: "go_test_backend/migrations"

id:
  # 0~1023，用于雪花算法 worker id
  worker_id: 1

registry:
  # 使用 Consul 做服务注册发现
  consul_addr: "http://127.0.0.1:8500"
  enable: true
  service_name: "go_test_backend"
  service_id: ""
  advertise_host: "127.0.0.1"
  advertise_port: 50051

consul_kv:
  # 使用 Consul KV 作为“动态配置”
  enable: true
  # 用户黑名单 key（value 支持 JSON 数组 或 逗号/换行分隔）
  user_blacklist_key: "go_test/user/blacklist"
  # 缓存秒数：避免每次查询都访问 Consul
  cache_ttl_seconds: 5

log:
  level: "info"
